name: CI/CD avec Vault

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3
        
      - name: Installer Vault CLI
        run: |
          wget https://releases.hashicorp.com/vault/1.14.0/vault_1.14.0_linux_amd64.zip
          unzip vault_1.14.0_linux_amd64.zip
          sudo mv vault /usr/local/bin/
          vault --version
          
      - name: Authentification avec Vault
        env:
          VAULT_ADDR: ${{ secrets.http://localhost:8200 }}
          VAULT_TOKEN: ${{ secrets.hvs.5gHu3rcJOQ9LIZXMhwfI9U22 }}
        run: |
          vault login $VAULT_TOKEN
          
      - name: Récupérer le secret depuis Vault
        env:
          VAULT_ADDR: ${{ secrets.http://localhost:8200 }}
        run: |
          API_KEY=$(vault kv get -field=api_key secret/my-app)
          echo "API_KEY=$API_KEY" >> $GITHUB_ENV
          
      - name: Utiliser le secret
        run: |
          echo "Le secret récupéré est : $API_KEY"
